import Head from "next/head";
import Link from "next/link";
import FallingVeggies from "../components/FallingVeggies";

export default function Home() {
  return (
    <>
      <Head>
        <title>PotsNPans</title>
        <meta
          name="Pots n' Pans provides you with the best of recipes from your current fridge inventory! Perfect for college students!"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="./images/favicon.svg" />
      </Head>
      <main className="flex h-screen w-full flex-col items-center justify-center">
        <Link
          href="/upload"
          className=" delay-80 rounded-full bg-purple-300 px-5 py-4 drop-shadow-lg transition ease-in-out hover:-translate-y-2"
        >
          <h1 className="bg-lightGreen text-white-200 z-10 rounded-full pl-20 pr-20 font-indie text-4xl text-white drop-shadow-lg">
            Let&apos;s Cook!
          </h1>
        </Link>
      </main>
    </>
  );
}
